#!/bin/bash
ln -sf ~/configs/.vimrc ~/.vimrc
ln -sf ~/configs/.Rprofile ~/.Rprofile
ln -sf ~/configs/.tmux.conf ~/.tmux.conf
echo If there weren\'t any error messages, then all symbolic links were created successfully.
