#!/bin/bash
ln -sf ~/.configs/.vimrc ~/.vimrc
ln -sf ~/.vim ~/.config/nvim
ln -sf ~/.configs/.vimrc ~/.config/nvim/init.vim
ln -sf ~/.configs/.Rprofile ~/.Rprofile
ln -sf ~/.configs/.tmux.conf ~/.tmux.conf
echo If there weren\'t any error messages, then all symbolic links were created successfully.
